#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "PokeJev — encontrar direcciones de memoria (X, Y, map_id)"

# ── Stage 1: instalar Cheat Engine ─────────────────────────────────────────
stage "Instalar Cheat Engine"
say "Cheat Engine no esta en winget, hay que bajarlo del sitio oficial."
open_url "https://www.cheatengine.org/downloads.php"
step "Descarga el instalador (boton grande 'Download Cheat Engine X.X')."
step "Ejecutalo. En las pantallas de instalacion puedes dar 'Next' a todo con las opciones por defecto."
note "El instalador a veces ofrece barras/software extra en el camino -- desmarca esas casillas si aparecen."
confirm "¿Ya terminaste de instalar Cheat Engine?" || warn "Instalalo antes de seguir y vuelve a correr este script."

# ── Stage 2: abrir juego + adjuntar proceso ─────────────────────────────────
stage "Abrir el juego y adjuntar Cheat Engine al proceso"
step "Abre Pokemon Anil y dejalo parado en modo exploracion (caminando por el mapa, sin menus abiertos)."
step "Abre Cheat Engine."
step "Click en el icono del monitor con la lupa (arriba a la izquierda, 'Select a process to open')."
step "En la lista busca 'Game.exe' (asi se llama el ejecutable de Pokemon Anil) y haz doble click."
note "Si ves un aviso de que Cheat Engine necesita permisos, dale que si (es normal, necesita leer memoria de otro proceso)."
confirm "¿Cheat Engine ya esta adjuntado a Game.exe (el titulo de la ventana de Cheat Engine deberia decir Game.exe)?" || warn "Adjuntalo antes de seguir."

# ── Stage 3: encontrar direccion de Posicion X ──────────────────────────────
stage "Encontrar la direccion de memoria de la Posicion X"
say "Vamos a encontrar donde guarda el juego tu coordenada X usando escaneo por valores que cambian."
step "En Cheat Engine, campo 'Value Type' (derecha) ponlo en '4 Bytes'."
step "Campo 'Scan Type' ponlo en 'Unknown initial value'."
step "Dale click a 'First Scan'. Esto escanea TODA la memoria del proceso (tarda unos segundos)."
step "Ahora, en el JUEGO, mueve a tu personaje varios pasos hacia la DERECHA (eso cambia X, no Y)."
step "Vuelve a Cheat Engine. Cambia 'Scan Type' a 'Changed value' y dale 'Next Scan'."
step "Repite: mueve otro par de pasos a la derecha en el juego, vuelve y dale 'Next Scan' con 'Changed value' de nuevo."
note "Cada ronda deberia reducir la lista de resultados. Repite 'moverse + Next Scan' hasta que queden pocas direcciones (idealmente menos de 10)."
step "Si quedan varias, mueve el personaje a la IZQUIERDA (X deberia bajar) y usa 'Scan Type: Decreased value' para filtrar mas."
step "Cuando quede 1 direccion (o un puñado claro), haz doble click en ella para agregarla a la lista de abajo (Cheat List)."
step "Ahi abajo, en la columna 'Address', copia el valor (algo como 'Game.exe+1A2B3C' o una direccion hexadecimal como '7FF6A1B2C3D4')."
ask DIRECCION_X "Pega la direccion de memoria de la Posicion X:"
write_env POKEJEV_ADDR_X "$DIRECCION_X"

# ── Stage 4: encontrar direccion de Posicion Y ──────────────────────────────
stage "Encontrar la direccion de memoria de la Posicion Y"
say "Mismo proceso, pero ahora moviendote ARRIBA/ABAJO en vez de izquierda/derecha."
step "Si quieres, puedes hacer un escaneo nuevo desde cero: boton 'New Scan' en Cheat Engine."
step "'Value Type: 4 Bytes', 'Scan Type: Unknown initial value', dale 'First Scan'."
step "En el juego, mueve al personaje varios pasos hacia ABAJO."
step "Vuelve a Cheat Engine, 'Scan Type: Changed value', 'Next Scan'."
step "Repite moverse hacia abajo + Next Scan un par de veces mas hasta que queden pocos resultados."
step "Si hace falta, mueve hacia ARRIBA y usa 'Decreased value' para terminar de aislarla."
step "Doble click en la direccion final para agregarla a la Cheat List y copia su 'Address'."
ask DIRECCION_Y "Pega la direccion de memoria de la Posicion Y:"
write_env POKEJEV_ADDR_Y "$DIRECCION_Y"

# ── Stage 5: encontrar direccion de Map ID ──────────────────────────────────
stage "Encontrar la direccion de memoria del Map ID"
say "El Map ID solo cambia cuando entras a otro mapa (otra ciudad, otro interior, otra ruta)."
step "'New Scan', 'Value Type: 4 Bytes', 'Scan Type: Unknown initial value', 'First Scan'."
step "En el juego, camina hacia la entrada de un edificio o hacia otra zona/mapa distinto (que cambie de pantalla/mapa)."
step "Vuelve a Cheat Engine, 'Scan Type: Changed value', 'Next Scan'."
step "El Map ID no deberia volver a cambiar hasta que cambies de mapa otra vez -- si tras un 'Changed value' quedan muchos resultados, entra a OTRO mapa distinto y repite 'Changed value' + 'Next Scan' una vez mas."
note "El Map ID suele ser un numero chico (0-500 aprox). Si ves una direccion cuyo valor actual es un numero asi de pequeño, es buena candidata."
step "Doble click en la direccion final para agregarla a la Cheat List y copia su 'Address'."
ask DIRECCION_MAPID "Pega la direccion de memoria del Map ID:"
write_env POKEJEV_ADDR_MAPID "$DIRECCION_MAPID"

# ── Stage 6: verificar estabilidad entre reinicios ──────────────────────────
stage "Verificar que las direcciones sobrevivan un reinicio del juego"
say "Las direcciones que encontraste pueden cambiar cada vez que abres el juego de nuevo (direcciones dinamicas)."
step "Cierra Pokemon Anil por completo y vuelve a abrirlo."
step "En Cheat Engine, vuelve a adjuntarte al proceso (icono de la lupa, 'Game.exe')."
step "Mira las 3 direcciones que guardaste en la Cheat List: si siguen mostrando valores que tienen sentido (tu X/Y actual, el map_id del mapa donde reapareciste), son ESTABLES -- no hace falta nada mas."
step "Si los valores se ven sin sentido (numeros gigantes o negativos raros) la direccion cambio -- hay que convertirla en un 'pointer' estable."
note "Para eso: click derecho sobre la direccion en la Cheat List -> 'Pointer scan for this address' -> dejar las opciones por defecto -> Cheat Engine busca cadenas de punteros estables (puede tardar varios minutos) -> cuando termine, elige el resultado con menos 'offsets' (mas simple) y copialo."
confirm "¿Las direcciones sobrevivieron el reinicio sin necesitar pointer scan?" && ESTABLES="si" || ESTABLES="no, requiere pointer scan (ver notas arriba)"
write_env POKEJEV_DIRECCIONES_ESTABLES "$ESTABLES"

finish

note "Estos valores quedaron en $ENV_FILE -- Claude los va a usar para armar la lectura de memoria en Python (ctypes ReadProcessMemory, solo lectura, sin inyectar nada)."
